"""empty message

Revision ID: c2d11fa52499
Revises: 1e19c3d32980
Create Date: 2020-09-25 22:08:41.596122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d11fa52499'
down_revision = '1e19c3d32980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('city', sa.String(), nullable=True))
    op.add_column('people', sa.Column('coach_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('color1', sa.String(), nullable=True))
    op.add_column('people', sa.Column('color2', sa.String(), nullable=True))
    op.add_column('people', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('people', 'catchphrase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('people', 'image')
    op.drop_column('people', 'color2')
    op.drop_column('people', 'color1')
    op.drop_column('people', 'coach_id')
    op.drop_column('people', 'city')
    # ### end Alembic commands ###
